config/routes.rb
Doclog::Application.routes.draw do
  resources :payments

  resources :machines

  resources :documents

  resources :transactions do 
    collection do 
      get 'receive'
    end
  end

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }
  
  namespace :api do
    resources :users 
  end

  get "home/index"
  root :to => "home#index"

  resources :home

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!, :except => "receive"

  # GET /transactions
  # GET /transactions.xml
  def index
    @transactions = Transaction.where("sender_mobile = ? or receiver_mobile = ? or receiver_email = ?", current_user.mobile, current_user.mobile, current_user.email).order("created_at")
    #print request.env.inspect
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
      format.json  { render :json => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = Transaction.where("id = ? and (sender_mobile = ? or receiver_mobile = ?)  ", params[:id], current_user.mobile, current_user.mobile).first
    unless @transacion
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
      format.json  { render :json => @transaction }
    end
    end
  end
  
  
  # POST /transactions
  # POST /transactions.xml
  def create
    @transaction = Transaction.new(params[:transaction])
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully created.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
        format.json  { render :json => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
        format.json  { render :json => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    @transaction = Transaction.new
    @transaction.build_document
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end
=begin
  # GET /transactions/1/edit
  def edit
    #@transaction = Transaction.find(params[:id])
    @transaction = Transaction.where("id = ? and (sender_mobile = ? or receiver_mobile = ?)  ", params[:id], current_user.mobile, current_user.mobile)
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    #@transaction = Transaction.find(params[:id])
    @transaction = Transaction.where("id = ? and (sender_mobile = ? or receiver_mobile = ?)  ", params[:id], current_user.mobile, current_user.mobile)

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end
=end
  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    #@transaction = Transaction.find(params[:id])
    @transaction = Transaction.where("id = ? and (sender_mobile = ? or receiver_mobile = ?)  ", params[:id], current_user.mobile, current_user.mobile)
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml  { head :ok }
    end
  end

  # Receive /transactions/receive
  def receive
    unless params[:transaction].blank? 
      unless (params[:transaction][:receiver_mobile].blank? or params[:transaction][:receiver_email].blank?) and params[:transaction][:document_secret].blank?
        @transaction = Transaction.get_document(params[:transaction][:receiver_mobile], params[:transaction][:receiver_email], params[:transaction][:document_secret]) 
        unless @transaction.blank?
          @document = @transaction.document
          respond_to do |format|
            format.html { send_file "public#{@document.doc.url(:original, false)}" , :type => "#{@document.doc_content_type}" }
            format.xml #receive.xml 
          end
        else
          respond_to do |format|
            @transaction = Transaction.new(params[:transaction])
            format.html { render :action =>  "receive"}
            format.xml  
          end
        end
      else
        respond_to do |format|
          @transaction = Transaction.new(params[:transaction])
          format.html { render :action =>  "receive"}
          format.xml  
         end
      end
    else
      @transaction = Transaction.new
      respond_to do |format|
        format.html # receive.html.erb
        format.xml  
      end
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
	def add_document(form_builder)
  	link_to_function "add", :id  => "add_document" do |page|
    	form_builder.fields_for :document, Document.new, :child_index => 'NEW_RECORD' do |document_form|
    	  html = render(:partial => 'document', :locals => { :f => document_form })
    	  #page << "$('add_document').insert({ before: '#{escape_javascript(html)}'.replace(/NEW_RECORD/g, new Date().getTime()) });"
    	  page << "$('#{escape_javascript(html)}'.replace(/NEW_RECORD/g, new Date().getTime())).insertBefore($('#add_document')); $('#add_document').remove();"
   		 end
  	end
	end
	
	def delete_document(form_builder)
    if form_builder.object.new_record?
      link_to_function("Remove this Document", "$(this).parent().remove()")
    else
      form_builder.hidden_field(:_delete) +
      link_to_function("Remove this Document", "this.up('fieldset').hide(); $(this).previous().value = '1'")
    end
  end
end

app/views/transactions/_document.html.erb
<fieldset>
    <% if !f.object.new_record? %>
        <%= image_tag f.object.doc.url %>
    <% end %>
    
    <%= f.file_field :doc %>
    <%= delete_document(f) %>
</fieldset>

app/views/transactions/_form.html.erb
<%= form_for(@transaction, :html => {:multipart => true}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><%= f.label :receiver_mobile %> <br>
  <%= f.text_field :receiver_mobile %> <br>
  Or <br>
  <%= f.label :receiver_email %> <br>
  <%= f.email_field :receiver_email %> </p>

  <%= f.hidden_field :sender_mobile, :value => current_user.mobile %>
  <p><%#= f.label :document_label %> <br>
  <%#= f.text_field :document_label %> </p>
  
  <%= add_document(f) %>
  
  <div class="actions">
    <%= f.submit "Edit Mail", :class => "button green" %>
  </div>
<% end %>

app/views/transactions/_form_send.html.erb
<%= form_for(@transaction, :html => {:multipart => true}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p><%= f.label :receiver_mobile %> <br>
  <%= f.text_field :receiver_mobile %> <br>
  Or <br>
  <%= f.label :receiver_email %> <br>
  <%= f.email_field :receiver_email %> </p>

  <%= f.hidden_field :sender_mobile, :value => current_user.mobile %>
 
  <%#= add_document(f) %>
  
  <%= f.fields_for :document, @transaction.document do |document_form| %>
      <p><%= document_form.label :doc, "Doc File" %>
      <%= document_form.file_field :doc %>
      <%= document_form.hidden_field :user_id, :value => current_user.id %>
      </p>
  <% end %>
  
  <div class="actions">
    <%= f.submit "Send Mail", :class => "button green" %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1><%= current_user.mobile %>'s Document Store</h1>
<%= link_to 'Send New eDakia mail', new_transaction_path, :class => "button gray" %>

<% unless @transactions.blank? %>
<table>
  <tr>
    <th>S.No</th>
    <th>Document</th>
    <th>Date</th>
    <th>Secret Code</th>
    <th></th>
  </tr>
	<% @transactions.each do |transaction| %>
	  <tr>
	    <td><%= link_to "#{transaction.id}", transaction %></td>
	    <td><%= link_to "#{transaction.document.doc_file_name}", transaction, :class => "white small" %></td>
	    <td><% if transaction.created_at.to_date == Date.today  %>
			<%=		transaction.created_at.strftime("%I:%M %p")	%>
			<% else %>
			<%=		transaction.created_at.strftime("%d-%b-%Y") %>
			<% end	 %>
		</td>
	    <td><%= transaction.document_secret %></td>
		<td><%= link_to "Download", transaction.document.doc.url(:original, false), :class => "button green small" %></td> 
	    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
	    <td><%= link_to 'x', transaction, :confirm => 'Are you sure?', :method => :delete %></td>
	 </tr>
	<% end %>
<% else %>
	<p>No eDakia Mail sent.</p>
	<p>Click "Send New eDakia Mail" and share documents on mobile number</p>
<% end %>
</table>

<br />

app/views/transactions/new.html.erb
<h1>Send new mail</h1>

<%= render 'form_send' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/receive.html.erb
<h1>Receive Document</h1>

<%= form_for(@transaction, :url => receive_transactions_path,  :html => {:method => :get}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited to retreive Document</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><%= f.label :receiver_mobile %> <br>
  <%= f.text_field :receiver_mobile %> </p>
  Or
  <p><%= f.label :receiver_email %> <br>
  <%= f.email_field :receiver_email %> </p>
  
  <p><%= f.label :document_secret %> <br>
  <%= f.text_field :document_secret %> </p>

  <div class="actions">
    <%= f.submit "Receive Mail", :class => "button blue" %>
  </div>
<% end %>

<%= link_to 'Login', new_user_session_url %> | <%= link_to 'Register', new_user_registration_url %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>
<p> <strong>Sender:</strong> <%= @transaction.sender_mobile %> </p>
<p> <strong>Receiver:</strong> <%= @transaction.receiver_mobile %> </p>
<p> <strong>Secret Code:<strong> <%= @transaction.document_secret %> </p>
<p> <strong>Date:<strong> <%= @transaction.created_at %> </p>
<p> <%= link_to "Download", @transaction.document.doc.url(:original, false), :class => "button green large" %></p>


<%= link_to 'Back to Document Store', transactions_path %>
<%#= link_to 'Edit', edit_transaction_path(@transaction) %>